/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ra57_2014_pnrs1_rtrk_taskmanager_statistics_NativeCalculation */

#ifndef _Included_ra57_2014_pnrs1_rtrk_taskmanager_statistics_NativeCalculation
#define _Included_ra57_2014_pnrs1_rtrk_taskmanager_statistics_NativeCalculation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ra57_2014_pnrs1_rtrk_taskmanager_statistics_NativeCalculation
 * Method:    calculateAngleOfAnimation
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_ra57_12014_pnrs1_rtrk_taskmanager_statistics_NativeCalculation_calculateAngleOfAnimation
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
